spring.application.name=PortfolioManager

# Finnhub API
finnhub.api.key=d767ophr01qm4b7t90u0d767ophr01qm4b7t90ug
finnhub.base.url=https://finnhub.io/api/v1

# Connection
spring.datasource.url=jdbc:mysql://localhost:3306/portfolio_manager
spring.datasource.username=root
spring.datasource.password=123456

# Schema generation
spring.jpa.hibernate.ddl-auto=update

# Hibernate extras
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

ollama.base-url=http://localhost:11434
ollama.model=llama3.2